### ISSUE TITLE
running into issue while making build-image

### ISSUE THREAD

**Issue by ramkrishnakadam** [Thelin90/datapains-trino-k8s#1]
I am trying to below command on macOS with Intel, but run into issues.

aa952580@AB62094 ~ % make build-image COMPONENT=metastore CONTEXT="tools/docker"
make: *** No rule to make target `build-image'.  Stop.

**Comment by Thelin90** [comment]
Hello.

This works just fine for me.

Given your output, are you sure you are inside the repository?

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6f2d080d-a998-4ab7-8329-91af9e928199">


The error you are seeing indicates you are in a directory which does not have the Makefile.

For ex:

<img width="615" alt="image" src="https://github.com/user-attachments/assets/7505c8c4-efcd-4f28-89e6-f9788b0eeeeb">

**Comment by ramkrishnakadam** [comment]
i was not inside repo. it worked after changing directory.
